name: Build Windows EXE

on: [push]


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller scapy
        
    - name: Build EXE
      run: |
        pyinstaller --onefile lldpwin.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pylldpwin
        path: dist/
