name: Build Windows EXE

on: [push]


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller scapy
        
    - name: Get WinDivert
      run: |
        curl -L -o Windivert.zip https://www.reqrypt.org/download/WinDivert-2.2.0-A.zip
        unzip Windivert.zip -d windivert
        cp Windivert/WinDivert-2.2.0-A/x86/WinDivert.dll .

    - name: Build EXE
      run: |
        pyinstaller --onefile \
        --add-data "WinDivert.dll;." \
        --hidden-import scapy.contrib.cdp \
        --hidden-import scapy.layers.lldp \
        lldpwin.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pylldpwin
        path: dist/
