name: Build app

on: [push]


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install netmiko openpyxl tqdm paramiko==3.5.0 argparse nuitka
        

    - name: Build myapp
      run: |
        nuitka --standalone --onefile --windows-disable-console --output-dir=dist myapp_scripts.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyappp
        path: dist/
